platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target ‘XMPageController’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'XMPageController'
end